install.packages("tidyverse")
install.packages("data.table")
install.packages("Matrix")
install.packages("R.utils")
install.packages("Seurat")
install.packages("sctransform")
install.packages("ggplot2")
install.packages("cowplot")
install.packages("harmony")
install.packages("msigdbr")
install.packages("statmod")

if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("glmGamPoi")
BiocManager::install("fgsea")
BiocManager::install("DESeq2")
BiocManager::install("infercnv")
BiocManager::install("biomaRt")
BiocManager::install("speckle")
BiocManager::install("miloR")
BiocManager::install("scater")

aremotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
remotes::install_github("LTLA/batchelor")
